
export const GENERIC_LABELS = [
  
  'food', 'dish', 'cuisine', 'meal', 'ingredient', 'produce', 'vegetable', 'fruit', 'meat', 'protein',
  'snack', 'breakfast', 'lunch', 'dinner', 'garnish', 'side', 'main', 'item', 'object', 'portion', 'serving',
  'recipe', 'cooking', 'cook', 'bake', 'boil', 'fry', 'roast', 'grill', 'steam', 'poach', 'simmer', 'blend', 'mix', 'prepare', 'preparation', 'marinate', 'season', 'spice', 'herb', 'condiment', 'sauce', 'dressing', 'stock', 'broth', 'base', 'bouillon',
  'plate', 'bowl', 'tray', 'pan', 'pot', 'board', 'grill', 'microwave', 'oven', 'stove', 'appliance', 'kitchen', 'counter', 'surface', 'utensil', 'fork', 'spoon', 'knife', 'napkin', 'cutlery', 'glass', 'cup', 'can', 'bottle', 'jar', 'box', 'bag', 'packet', 'carton', 'container', 'package', 'wrapper', 'cover', 'lid', 'cap', 'seal',
  'table', 'cloth', 'background', 'advertisement', 'menu', 'receipt', 'barcode', 'label', 'logo', 'brand', 'sign', 'poster', 'flyer', 'banner', 'ad', 'instruction', 'manual', 'guide', 'book', 'magazine', 'newspaper',
  'unknown', 'stuff', 'thing', 'product', 'mix', 'blend', 'powder', 'solid', 'liquid', 'spread', 'paste', 'dip', 'topping', 'filling', 'layer', 'coating', 'dough', 'batter', 'mixture', 'extract', 'essence', 'flavor', 'taste', 'aroma', 'smell', 'color', 'texture', 'appearance', 'portion', 'piece', 'slice', 'crumb', 'crust', 'sample', 'bit', 'drop', 'dash', 'pinch', 'hint', 'touch', 'trace', 'amount', 'quantity', 'portion', 'serving', 'helping', 'batch', 'lot', 'set', 'group', 'selection', 'variety', 'assortment', 'combination', 'mix', 'blend', 'fusion', 'creation', 'preparation', 'presentation',
  'leaf', 'leaves', 'greens', 'root', 'root vegetable', 'stalk', 'stem', 'flower', 'petal', 'seed', 'shell', 'skin', 'peel', 'core', 'pit', 'stone', 'bone', 'fat', 'oil', 'grease', 'fiber', 'husk', 'pod', 'twig', 'branch', 'bark', 'wood', 'stick', 'thorn', 'spine', 'needle', 'bud', 'shoot', 'sprout', 'sap', 'gum', 'resin', 'pulp', 'rind', 'zest',
  'drink', 'beverage', 'alcohol', 'wine', 'beer', 'cocktail', 'juice', 'soda', 'water', 'tea', 'coffee', 'espresso', 'latte', 'cappuccino', 'mocha', 'chai', 'matcha', 'smoothie', 'milkshake', 'shake', 'tonic', 'energy drink', 'sports drink', 'mocktail',
  'side dish', 'main course', 'appetizer', 'starter', 'dessert', 'entree', 'garnish', 'snack', 'breakfast', 'lunch', 'dinner', 'brunch', 'supper', 'buffet', 'banquet', 'feast', 'spread', 'platter', 'combo', 'sampler',
  'sweet and sour', 'sweet and sour chicken', 'fried rice', 'curry', 'stew', 'soup', 'salad', 'sandwich', 'wrap', 'roll', 'pizza', 'burger', 'pasta', 'noodle', 'noodles', 'cake', 'pie', 'cookie', 'biscuit', 'bread', 'toast', 'muffin', 'pancake', 'waffle', 'omelette', 'scramble', 'patty', 'cutlet', 'sausage', 'nugget', 'stick', 'ball', 'cube', 'chunk', 'strip', 'ring', 'wheel', 'bar', 'log', 'sheet', 'square', 'triangle', 'round', 'flatbread', 'taco', 'burrito', 'quesadilla', 'enchilada', 'samosa', 'pakora', 'dumpling', 'spring roll', 'egg roll', 'dim sum', 'bao', 'gyoza', 'pierogi', 'empanada', 'calzone', 'stromboli', 'turnover', 'tart', 'galette', 'clafoutis', 'souffle', 'flan', 'custard', 'pudding', 'mousse', 'trifle', 'parfait', 'sundae', 'ice cream', 'gelato', 'sorbet', 'granita', 'popsicle', 'fudge', 'brownie', 'blondie', 'barfi', 'laddu', 'halwa', 'jalebi', 'gulab jamun', 'rasgulla', 'kheer', 'payasam', 'sheera', 'modak', 'peda', 'sandesh', 'malpua', 'shrikhand', 'basundi', 'rabri', 'phirni', 'seviyan', 'falooda', 'kulfi', 'mithai','tofu','staple food','yuvarlakia',
  'leftover', 'remains', 'scrap', 'waste', 'garbage', 'trash', 'compost', 'recycle', 'clean', 'dirty', 'fresh', 'stale', 'old', 'new', 'raw', 'cooked', 'burnt', 'overcooked', 'undercooked', 'spoiled', 'rotten', 'expired', 'preserved', 'pickled', 'fermented', 'smoked', 'dried', 'dehydrated', 'frozen', 'chilled', 'cold', 'hot', 'warm', 'room temperature', 'ambient', 'seasonal', 'local', 'imported', 'organic', 'natural', 'artificial', 'synthetic', 'processed', 'packaged', 'homemade', 'store-bought', 'restaurant', 'takeout', 'delivery', 'fast food', 'street food', 'catering', 'buffet', 'banquet', 'party', 'event', 'occasion', 'holiday', 'festival', 'celebration',
  'about','above','additional','after','against','air','all','almost','already','also',
'alternative','always','amount','another','any','anytime','approximately','around','artificial',
'as','available','avoid','back','basic','before','below','best','better','between',
'beyond','brand','bring','by','care','certain','chemical','clean','close','common',
'comparable','complete','complex','condition','contains','continue','control','cool',
'cost','current','daily','damage','dark','day','deep','depending','designed','detail',
'different','difficult','direct','does','down','dry','during','each','early','easily',
'easy','effect','either','empty','enough','entire','especially','essential','even','every',
'everyday','exact','example','except','excess','extra','fair','false','fast','few',
'final','finish','first','fit','following','for','former','found','free','fresh',
'full','further','general','generic','gentle','good','gradual','great','half',
'hand','hard','have','help','high','hold','home','how','however','immediate',
'important','improve','in','include','increase','instead','just','keep','kind','large',
'last','later','least','less','let','light','like','limited','little','local',
'long','low','made','main','make','many','may','medium','might','minimal',
'minimum','more','most','much','must','natural','near','necessary','need','new',
'next','no','non','normal','not','nothing','now','obvious','often','old',
'on','once','only','open','optional','ordinary','original','other','otherwise','our',
'out','over','pack','part','particular','past','per','perhaps','place','plain',
'point','possible','power','present','previous','primary','prior','product','proper','provide',
'public','quick','quite','random','rare','rather','ready','real','recent','regular',
'remain','replace','require','result','right','safe','same','sample','second','see',
'seldom','sensitive','separate','severe','several','shall','short','should','simple','since',
'slow','small','smooth','so','some','sometimes','soon','special','specific','standard',
'start','still','store','strong','such','suitable','supply','support','sure','system',
'take','technical','temporary','test','than','that','the','their','them','then',
'there','these','they','thing','this','those','through','thus','time','together',
'too','top','total','toward','true','try','turn','typical','under','unless',
'until','up','upon','use','usual','various','very','wait','warm','way',
'we','well','when','where','whether','which','while','whole','why','wide',
'will','with','within','without','wonder','work','worse','worst','worth','wrong',
'yes','yet','zero','absolutely','accordingly','across','afterward','alike','alone','along',
'although','altogether','among','apart','apparently','approximately','aside','associated','away','awfully',
'barely','basically','beforehand','behind','beneath','beside','besides','beyond','briefly','broadly',
'certainly','chiefly','clearly','closely','commonly','completely','concerning','consequently','considerably','consistently',
'constantly','conversely','correctly','currently','decidedly','deeply','definitely','deliberately','directly','distinctly',
'duly','easily','elsewhere','entirely','equally','especially','essentially','eventually','exactly','exceedingly',
'exclusively','explicitly','externally','fairly','familiarly','far','fast','finally','fluently','formerly',
'forth','freely','frequently','fully','furthermore','generally','gently','gradually','greatly','hardly',
'hastily','heavily','highly','hopefully','however','immediately','importantly','incidentally','increasingly','indeed',
'indirectly','inevitably','initially','inside','instead','intensely','internally','invariably','jointly','largely',
'lastly','later','lately','least','legally','less','lightly','likely','literally','locally',
'loosely','mainly','markedly','materially','merely','mildly','moreover','mostly','namely','naturally',
'nearly','necessarily','nevertheless','nonetheless','normally','notably','nowadays','nowhere','occasionally','often',
'only','openly','ordinarily','originally','otherwise','outdoors','outright','outside','outward','overly',
'particularly','partly','perfectly','permanently','perhaps','plainly','positively','potentially','practically','precisely',
'presently','previously','primarily','probably','properly','purely','quickly','quietly','rarely','readily',
'really','recently','regularly','relatively','repeatedly','rightly','roughly','sadly','safely','seldom',
'seriously','severely','shortly','similarly','simply','sincerely','slightly','slowly','smoothly','softly',
'somehow','sometimes','somewhat','soon','specifically','specially','steadily','strictly','strongly','suddenly',
'suitably','surely','temporarily','tightly','totally','truly','typically','ultimately','undoubtedly','unfortunately',
'universally','unlike','unnecessarily','usually','utterly','vastly','verbally','virtually','visibly','voluntarily',
'wholly','widely','wisely','wrongly','yet','accordance','addition','advantage','affect','against',
'appearance','approach','attention','awareness','balance','basis','belief','benefit','case','cause',
'certainty','chance','choice','circumstance','concept','concern','conclusion','condition','connection','consequence',
'consideration','contrast','control','course','danger','decision','definition','degree','demand','description',
'desire','difference','difficulty','direction','disadvantage','discovery','discussion','distance','distinction','distribution',
'education','effect','effort','emphasis','end','error','example','exception','experience','fact',
'failure','feeling','field','figure','focus','form','function','goal','growth','guide',
'idea','impact','importance','impression','improvement','information','instance','intention','interest','issue',
'knowledge','lack','level','limit','manner','meaning','measure','method','mistake','mode',
'moment','nature','need','notion','objective','occasion','opinion','option','order','outcome',
'outline','overall','pattern','period','phenomenon','place','plan','point','position','possibility',
'practice','preference','preparation','presence','principle','problem','process','purpose','range','rate',
'reason','reference','relation','relationship','remark','requirement','respect','result','risk','role',
'rule','situation','solution','stage','standard','state','statement','status','step','strategy',
'strength','structure','subject','success','suggestion','task','tendency','term','test','theory',
'thing','thought','trend','truth','type','use','value','variation','view','way','word','work',
'ribs', 'steak', 'pork ribs',
];
